# Generated by Django 5.1.6 on 2025-10-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlUsuario', '0001_initial'),
        ('hospital_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jorna_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('turno', models.CharField(choices=[('dia', 'Diurno (7:00 a 15:00)'), ('tarde', 'Vespertino (15:00 a 23:00)'), ('noche', 'Nocturno (23:00 a 7:00)'), ('on-call', 'Guardia')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_temporales/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('permite_turno', models.BooleanField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='hospital_personal.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiosDiagnosticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_resultado', models.CharField(choices=[('img', 'Imagen'), ('lab', 'Laboratorio'), ('fisio', 'Fisiológico'), ('eval', 'Evaluación clínica')], max_length=100)),
                ('nombre_estudio', models.CharField(max_length=200)),
                ('especialidad', models.ManyToManyField(related_name='EspecialidadesDelEstudio', to='hospital_personal.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('lab', 'Laboratorio'), ('hab', 'Habitación'), ('qui', 'Quirófano'), ('cons', 'Consultorio'), ('oficina_resultados', 'Oficina de Resultados')], max_length=50)),
                ('piso', models.IntegerField()),
                ('sala', models.PositiveIntegerField(unique=True)),
                ('abreviacion', models.CharField(max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_critico', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Medicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_uso', models.CharField(blank=True, max_length=255, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='hospital_personal.consultas')),
                ('recetada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_estudio', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('noRealizado', 'No realizado')], default='pendiente', max_length=20)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='hospital_personal.consultas')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.usuario')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_estudios', to='hospital_personal.estudiosdiagnosticos')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estructura', models.JSONField()),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla', to='hospital_personal.estudiosdiagnosticos')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.departamento')),
                ('lugar', models.ManyToManyField(related_name='servicios_diagnostico', to='hospital_personal.lugar')),
            ],
        ),
        migrations.AddField(
            model_name='estudiosdiagnosticos',
            name='servicio_diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.serviciodiagnostico'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_turno', models.DateField()),
                ('horario_turno', models.CharField(choices=[('dia', 'Diurno(7:00 a 15:00)'), ('tarde', 'Vespertino(15:00 a 23:00)'), ('noche', 'Nocturno(23:00 a 7:00)'), ('on-call', 'Guardia')], default='dia', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido'), ('noAsistio', 'No asistio'), ('reprogramado', 'Reprogramado')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('asistio', models.BooleanField(default=False)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.especialidades')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='hospital_pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='consultas',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='hospital_personal.turno'),
        ),
        migrations.CreateModel(
            name='TurnoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_turno', models.DateField()),
                ('horario_turno', models.CharField(choices=[('dia', 'Diurno(7:00 a 15:00)')], default='dia', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido'), ('noAsistio', 'No asistio'), ('realizado', 'Realizado')], default='pendiente', max_length=20)),
                ('asistio', models.BooleanField(default=False)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.lugar')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turnoEstudio', to='hospital_personal.ordenestudio')),
                ('servicio_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.serviciodiagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe', models.TextField()),
                ('datos_especificos', models.JSONField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='resultados/')),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.usuario')),
                ('imagenes', models.ManyToManyField(blank=True, related_name='resultados', to='hospital_personal.resultadoimagen')),
                ('turno_estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='hospital_personal.turnoestudio')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioLugarTrabajoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.jorna_laboral')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuariosAsignadosAEsteLugar', to='controlUsuario.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'jornada'), name='unique_usuario_jornada')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRolProfesionalAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.rolesprofesionales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidadesUsuario', to='controlUsuario.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol_profesional'), name='unique_usuario_rol_profesional')],
            },
        ),
    ]
