# Generated by Django 5.1.6 on 2025-10-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolugartrabajoasignado',
            name='rolProfesionalAsignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.usuariorolprofesionalasignado'),
        ),
    ]
