# Generated by Django 5.1.6 on 2025-10-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0002_usuariolugartrabajoasignado_rolprofesionalasignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('cons', 'Consultorio'), ('lab', 'Laboratorio'), ('diag', 'Sala de diagnostico'), ('unidad_atenc', 'Unidad de atención'), ('qui', 'Sala de procedimiento'), ('hab', 'Habitación'), ('area_apoyo', 'Áreas de apoyo')], max_length=50),
        ),
    ]
