# Generated by Django 5.1.6 on 2025-10-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0003_alter_lugar_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('cons', 'Consultorio'), ('lab', 'Laboratorio'), ('img', 'Sala de imagenología'), ('diag_func', 'Sala de diagnóstico funcional'), ('unidad_atenc', 'Unidad de atención'), ('qui', 'Quirófano'), ('proc', 'Sala de procedimiento no quirúrgico'), ('hab', 'Habitación'), ('area_apoyo', 'Área de apoyo')], max_length=50),
        ),
    ]
