# Generated by Django 5.1.6 on 2025-10-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0004_alter_lugar_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.lugar'),
        ),
    ]
