# Generated by Django 5.1.6 on 2025-10-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0005_turno_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='capacidad_diaria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciodiagnostico',
            name='capacidad_diaria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
