# Generated by Django 5.1.6 on 2025-10-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_pacientes', '0001_initial'),
        ('hospital_personal', '0006_especialidades_capacidad_diaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestudio',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenesPaciente', to='hospital_pacientes.paciente'),
            preserve_default=False,
        ),
    ]
