# Generated by Django 5.1.6 on 2025-10-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0007_ordenestudio_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenestudio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'En espera de programación'), ('programado', 'Programado'), ('vencida', 'Orden vencida')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='turnoestudio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('analisis', 'En análisis'), ('noAsistio', 'No asistio'), ('realizado', 'Realizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariolugartrabajoasignado',
            name='rolProfesionalAsignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RolesProfesionalesAsignados', to='hospital_personal.usuariorolprofesionalasignado'),
        ),
    ]
