# Generated by Django 5.2.7 on 2025-11-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0002_initial'),
        ('hospital_pacientes', '0001_initial'),
        ('hospital_personal', '0008_alter_ordenestudio_estado_alter_turnoestudio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorolprofesionalasignado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolesProfesionalesUsuario', to='controlUsuario.usuario'),
        ),
        migrations.CreateModel(
            name='AsignacionesHabitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.lugar')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEnfermero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.usuario')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.jorna_laboral')),
                ('asignacion_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.asignacioneshabitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionesEnfermero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signos_vitales', models.TextField()),
                ('observaciones', models.TextField()),
                ('procedimientos_realizados', models.TextField()),
                ('medicacion_administrada', models.TextField(blank=True, null=True)),
                ('fecha_y_horario', models.DateTimeField(auto_now_add=True)),
                ('asignacion_enfermero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.asignacionenfermero')),
            ],
        ),
    ]
