# Generated by Django 5.2.7 on 2025-11-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0009_alter_usuariorolprofesionalasignado_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='unidad',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'unidad_atenc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones', to='hospital_personal.lugar'),
        ),
    ]
