# Generated by Django 5.2.7 on 2025-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0010_lugar_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='sala',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
