# Generated by Django 5.2.7 on 2025-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0011_alter_lugar_capacidad_alter_lugar_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioneshabitaciones',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
