# Generated by Django 5.2.7 on 2025-11-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0003_rolesprofesionales_departamento'),
        ('hospital_personal', '0012_alter_asignacioneshabitaciones_fecha_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asignacion_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.asignacioneshabitaciones')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignacion_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.asignacioneshabitaciones')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AltaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_principal', models.TextField()),
                ('diagnosticos_secundarios', models.TextField(blank=True, null=True)),
                ('tratamiento_realizado', models.TextField()),
                ('indicaciones_post_alta', models.TextField(blank=True, null=True)),
                ('asignacion_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.asignacionmedico')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionesMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucion_clinica', models.TextField()),
                ('indicaciones', models.TextField()),
                ('fecha_y_horario', models.DateTimeField(auto_now_add=True)),
                ('asignacion_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.asignacionmedico')),
            ],
        ),
    ]
