# Generated by Django 5.2.7 on 2025-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0013_altaadministrativa_asignacionmedico_altamedica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionesmedico',
            name='diagnostico',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observacionesmedico',
            name='motivo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
