# Generated by Django 5.2.7 on 2025-11-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0014_observacionesmedico_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionmedico',
            name='asignacion_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoAsignado', to='hospital_personal.asignacioneshabitaciones'),
        ),
    ]
