# Generated by Django 5.2.7 on 2025-11-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0015_alter_asignacionmedico_asignacion_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionenfermero',
            name='asignacion_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfermerosAsignados', to='hospital_personal.asignacioneshabitaciones'),
        ),
    ]
