# Generated by Django 5.2.7 on 2025-11-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0016_alter_asignacionenfermero_asignacion_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacionesenfermero',
            name='procedimientos_realizados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
