# Generated by Django 5.2.7 on 2025-11-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_pacientes', '0001_initial'),
        ('hospital_personal', '0017_alter_observacionesenfermero_procedimientos_realizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioneshabitaciones',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitacionAsignada', to='hospital_pacientes.paciente'),
        ),
    ]
