# Generated by Django 5.2.7 on 2025-11-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0018_alter_asignacioneshabitaciones_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altaadministrativa',
            name='observaciones',
        ),
    ]
