# Generated by Django 5.2.7 on 2025-11-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0019_remove_altaadministrativa_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altamedica',
            name='asignacion_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altaMedica', to='hospital_personal.asignacionmedico'),
        ),
    ]
