# Generated by Django 5.2.7 on 2025-11-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0020_alter_altamedica_asignacion_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altaadministrativa',
            name='asignacion_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altaAdministrativa', to='hospital_personal.asignacioneshabitaciones'),
        ),
    ]
