# Generated by Django 5.2.7 on 2025-11-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0003_rolesprofesionales_departamento'),
        ('hospital_personal', '0021_alter_altaadministrativa_asignacion_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TurnosDelMedico', to='controlUsuario.usuario'),
        ),
    ]
