# Generated by Django 5.2.7 on 2025-11-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0023_alter_turno_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoestudio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('analisis', 'En análisis'), ('noAsistio', 'No asistio'), ('realizado', 'Realizado')], default='pendiente', max_length=20),
        ),
    ]
