# Generated by Django 5.2.7 on 2025-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0024_alter_turnoestudio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolugartrabajoasignado',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('desasignado', 'Desasignado')], default='asignado', max_length=50),
        ),
    ]
