# Generated by Django 5.2.7 on 2025-12-05 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0025_usuariolugartrabajoasignado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiosdiagnosticos',
            name='servicio_diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiosDelServicio', to='hospital_personal.serviciodiagnostico'),
        ),
    ]
