# Generated by Django 5.2.7 on 2025-12-16 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_pacientes', '0002_paciente_numero_paciente'),
        ('hospital_personal', '0026_alter_estudiosdiagnosticos_servicio_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReactivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_pacientes.paciente')),
            ],
        ),
    ]
