# Generated by Django 5.2.7 on 2025-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0027_solicitudreactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreactivacion',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudreactivacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizado', 'Finalizado')], default='pendiente', max_length=10),
        ),
    ]
