# Generated by Django 5.2.7 on 2025-12-17 02:13

import hospital_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0028_solicitudreactivacion_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreactivacion',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=hospital_personal.models.SolicitudReactivacion.vencimiento_default),
        ),
    ]
