# Generated by Django 5.2.7 on 2025-12-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0030_solicitudreactivacion_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenestudio',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
