# Generated by Django 5.2.7 on 2026-01-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0005_alter_rolesprofesionales_especialidad_and_more'),
        ('hospital_personal', '0031_ordenestudio_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.departamento'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='piso',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='unidad',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'unidad_atenc'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hospital_personal.lugar'),
        ),
        migrations.AlterField(
            model_name='solicitudreactivacion',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='solicitudreactivacion',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitudreactivacion',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitudreactivacion',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuariorolprofesionalasignado',
            name='rol_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.rolesprofesionales'),
        ),
        migrations.AlterField(
            model_name='usuariorolprofesionalasignado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolesProfesionalesUsuario', to='controlUsuario.usuario'),
        ),
    ]
