# Generated by Django 5.2.7 on 2026-01-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0005_alter_rolesprofesionales_especialidad_and_more'),
        ('hospital_pacientes', '0003_alter_paciente_numero_paciente_and_more'),
        ('hospital_personal', '0032_alter_lugar_departamento_alter_lugar_piso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='hospital_personal.turno'),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='capacidad_diaria',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to='hospital_personal.departamento'),
        ),
        migrations.AlterField(
            model_name='estudiosdiagnosticos',
            name='servicio_diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiosDelServicio', to='hospital_personal.serviciodiagnostico'),
        ),
        migrations.AlterField(
            model_name='medicaciones',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaciones', to='hospital_personal.consultas'),
        ),
        migrations.AlterField(
            model_name='medicaciones',
            name='recetada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.usuario'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.usuario'),
        ),
        migrations.AlterField(
            model_name='ordenestudio',
            name='tipo_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_estudios', to='hospital_personal.estudiosdiagnosticos'),
        ),
        migrations.AlterField(
            model_name='plantillaestudio',
            name='estudio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='plantilla', to='hospital_personal.estudiosdiagnosticos'),
        ),
        migrations.AlterField(
            model_name='serviciodiagnostico',
            name='capacidad_diaria',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='serviciodiagnostico',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.departamento'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.especialidades'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario_turno',
            field=models.CharField(choices=[('dia', 'Diurno(7:00 a 15:00)'), ('tarde', 'Vespertino(15:00 a 23:00)'), ('noche', 'Nocturno(23:00 a 7:00)'), ('on-call', 'Guardia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='hospital_pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnosDelMedico', to='controlUsuario.usuario'),
        ),
        migrations.AlterField(
            model_name='usuariolugartrabajoasignado',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.jorna_laboral'),
        ),
        migrations.AlterField(
            model_name='usuariolugartrabajoasignado',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.lugar'),
        ),
        migrations.AlterField(
            model_name='usuariolugartrabajoasignado',
            name='rolProfesionalAsignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RolesProfesionalesAsignados', to='hospital_personal.usuariorolprofesionalasignado'),
        ),
        migrations.AlterField(
            model_name='usuariolugartrabajoasignado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuariosAsignadosAEsteLugar', to='controlUsuario.usuario'),
        ),
    ]
