# Generated by Django 5.2.7 on 2026-01-13 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0005_alter_rolesprofesionales_especialidad_and_more'),
        ('hospital_personal', '0033_alter_consultas_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoestudio',
            name='cargado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.usuario'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='turno_estudio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado', to='hospital_personal.turnoestudio'),
        ),
        migrations.AlterField(
            model_name='turnoestudio',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='turnoEstudio', to='hospital_personal.ordenestudio'),
        ),
        migrations.AlterField(
            model_name='turnoestudio',
            name='servicio_diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.serviciodiagnostico'),
        ),
    ]
