# Generated by Django 5.1.6 on 2025-10-20 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlUsuario', '0001_initial'),
        ('hospital_personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesprofesionales',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.especialidades'),
        ),
        migrations.AddField(
            model_name='rolesprofesionales',
            name='servicio_diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.serviciodiagnostico'),
        ),
        migrations.AddField(
            model_name='rolesprofesionales',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.tiposusuarios'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.tiposusuarios'),
        ),
    ]
