# Generated by Django 5.2.7 on 2025-11-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0002_initial'),
        ('hospital_personal', '0009_alter_usuariorolprofesionalasignado_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesprofesionales',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.departamento'),
        ),
    ]
