# Generated by Django 5.2.7 on 2026-01-13 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0004_alter_persona_sexo'),
        ('hospital_personal', '0031_ordenestudio_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesprofesionales',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.especialidades'),
        ),
        migrations.AlterField(
            model_name='rolesprofesionales',
            name='servicio_diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital_personal.serviciodiagnostico'),
        ),
        migrations.AlterField(
            model_name='rolesprofesionales',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlUsuario.tiposusuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
