# Generated by Django 5.1.6 on 2025-10-20 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenorACargoDePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('HIJO', 'Hijo/a'), ('NIETO', 'Nieto/a'), ('SOBRINO', 'Sobrino/a'), ('ABUELO', 'Abuelo/a'), ('HERMANO', 'Hermano/a mayor'), ('TUTOR_LEGAL', 'Tutor Legal')], max_length=50, verbose_name='Parentesco con el menor')),
                ('adulto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menores_a_cargo', to='hospital_pacientes.paciente')),
                ('menor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='hospital_pacientes.paciente')),
            ],
        ),
    ]
