# Generated by Django 5.2.7 on 2025-12-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_paciente',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
