# Generated by Django 5.2.7 on 2026-01-13 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_pacientes', '0002_paciente_numero_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_paciente',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
